### ISSUE TITLE
General, unfiltered feedback

### ISSUE THREAD

**Issue by teddywilson** [joaoritter/fountain.finance#1]
I took a quick glance at [Sustainers.sol](https://github.com/joaoritter/sustainers.money/blob/main/contracts/Sustainers.sol) and took a few notes – I figured this was the easiest way to leave some feedback, which I time-boxed to ~15 minutes.

Worth noting I lack (almost) a complete understanding of smart contracts, particularly at the implementation level, so my comments are decently general.

# Nomenclature

Some of naming in the codebase is a bit confusing, but not necessarily unbearable. Thoughts to follow.

## Organism
"Organism" is pretty cerebral and makes some of the other concepts here harder to wrap your head around. As I see it, this is the top-level, all-encompassing abstraction, which holds Purposes, Sustainers, Stewards, etc. Maybe it's too constricting, but I think something along the lines of "Market" or "Marketplace" feels a bit more apt here.

## Steward
Maybe I get too hung up on naming, but I feel like there's something to be said about shooting for an elementary reading level when it comes to naming conventions – particularly when you're engaging with people that don't necessarily speak english. "Steward" has always been a weird word to me; I guess that's because it's pretty abstract and can mean many different things. Why not call this "creator", "owner", "admin", etc.? 

I feel like these two changes could offer substantially better readability in the codebase.

### Naming nits
* "withdrawl" -> "withdraw", or "withdrawal"
* Purpose.want – is "want" typical nomenclature for a token? If not, why not just "funding_token"?

# Structure

## One-to-one mappings / overall design
It seems like there are a few mappings that are currently one-to-one that could easily be one-to-many, namely `address => Purpose`.  I see that there is also a notion of `nextPurposes`, which is admittedly a bit confusing. Is there a reason that people are only allowed a single active purpose and a single next one?

I guess this leads to a larger question about the design of `function sustain(address _steward, uint256 _amount)`. It seems the general principle here is that you're sustaining an individual, rather than a purpose. From a product perspective - is this a 'product'? – it's a bit misleading, but perhaps it's intentional. In the conventional fundraising world, funding is often directed towards the purpose itself and the stewards come secondary.

Perhaps my confusion comes from a misunderstanding of blockchain, but would it be at all possible to decouple the receiving address of the purpose from the steward itself? I.e., is it possible to generate a new address solely for each purpose, upon creation? This could offer more extensibility down the line if multiple stewards become owners of a purpose and have access to its funds.

I don't know, I'm rambling. Maybe this isn't the best forum for these kinds of questions.

## Duplicated data
I see that currently sustained amount `sustainment` can essentially be derived from `netSustainments`. It may be worth extracting the former into a helper function to only hold one source of data for the currently sustained amount. If those get out of sync somehow, things could get ugly.

-----

Okay, that's 15 minutes. I didn't really get through most of it, but let's catch up more on it soon. Great work, the idea here is really something unique and powerful.

**Comment by joaoritter** [comment]
thanks!
